using UnityEngine;
using TMPro;

public class TimeAliveMoney : MonoBehaviour
{
    public float moneyPerSecond = 0.1f;
    public TMP_Text moneyText;
    public TMP_Text totalMoneyText; 
    public Player player;
    private float timeAlive = 0f;
    private float totalMoneyEarned = 0f;

    private void Start()
    {
        totalMoneyEarned = PlayerPrefs.GetFloat("Money", 0f); 
        totalMoneyText.text = ((int)totalMoneyEarned).ToString() + "$"; 
    }

    void Update()
    {
        if (player.gameStarted && player.isAlive == true) {
            timeAlive += Time.deltaTime;
            float earnedMoney = timeAlive * moneyPerSecond;
            if (moneyText != null)
                moneyText.SetText(((int)earnedMoney).ToString() + "$");
        }
    }

    public void OnPlayerDeath()
    {
        totalMoneyEarned += timeAlive * moneyPerSecond;
        SaveMoney();
        timeAlive = 0f;
        totalMoneyText.text = ((int)totalMoneyEarned).ToString() + "$"; 
    }


    private void SaveMoney()
    {
        PlayerPrefs.SetFloat("Money", totalMoneyEarned);
        PlayerPrefs.Save();
    }
}